In [3]:
!pip install psycopg2

In [6]:
import sqlalchemy

uri = 'postgresql://postgres:admin@localhost:5432/imdb'

engine = sqlalchemy.create_engine(uri)
metadata = sqlalchemy.MetaData()
metadata.reflect(bind=engine)

In [13]:
for table in metadata.sorted_tables:
    print(table)
    
print(len(metadata.tables))

aka_name
aka_title
cast_info
char_name
comp_cast_type
company_name
company_type
complete_cast
info_type
keyword
kind_type
link_type
movie_companies
movie_info
movie_keyword
movie_link
name
person_info
role_type
title
20


In [26]:
import pandas as pd


df = pd.read_sql('SELECT * FROM title TABLESAMPLE SYSTEM(0.01)', con=engine.connect())

In [25]:
metadata.tables['title']

Table('title', MetaData(bind=None), Column('id', INTEGER(), table=<title>, primary_key=True, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7fda94153a58>, for_update=False)), Column('title', TEXT(), table=<title>, nullable=False), Column('imdb_index', VARCHAR(length=12), table=<title>), Column('kind_id', INTEGER(), table=<title>, nullable=False), Column('production_year', INTEGER(), table=<title>), Column('imdb_id', INTEGER(), table=<title>), Column('phonetic_code', VARCHAR(length=5), table=<title>), Column('episode_of_id', INTEGER(), table=<title>), Column('season_nr', INTEGER(), table=<title>), Column('episode_nr', INTEGER(), table=<title>), Column('series_years', VARCHAR(length=49), table=<title>), Column('md5sum', VARCHAR(length=32), table=<title>), schema=None)

In [25]:
np.unique([1, 2, 'NULL'], return_inverse=True)

(array(['1', '2', 'NULL'],
       dtype='<U21'), array([0, 1, 2]))

In [46]:
import math
import random

import pandas as pd
from scipy.stats import chi2_contingency


def to_numeric(x):
    _, num = np.unique(x, return_inverse=True)
    return num

def calc_mutual_info(x: pd.Series, y: pd.Series, bins='sqrt'):
    """Calculates the mutual information between two series."""

    # Determine the number of bins
    if bins == 'sqrt':
        bins = math.ceil(math.log(len(x)))

    # Convert the arrays to if they are not numeric
    null_fill = random.random()
    x = to_numeric(x.fillna(null_fill))
    y = to_numeric(y.fillna(null_fill))

    counts = np.histogram2d(x, y, bins)[0]
    
    print(x)
    print(y)
    print(counts)
    
    g, p, dof, expected = chi2_contingency(counts, lambda_='log-likelihood')
    mi = 0.5 * g / counts.sum()
    return mi

x = pd.Series(np.random.normal(size=10000))
y = x + 1

calc_mutual_info(x, y)

[9030 6448 1016 ..., 1798 4615 1122]
[9030 6448 1016 ..., 1798 4615 1122]
[[ 1000.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.  1000.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.  1000.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.  1000.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.  1000.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.  1000.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.  1000.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.  1000.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.  1000.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.  1000.]]


2.3025850929940459

In [64]:
from sklearn import metrics


x = [0, 1, 2]
y = [1.1, 1.1, 1.1]


metrics.mutual_info_score(x, y)

1.0986122886681096